### ISSUE TITLE
Error with /zcord stats

### ISSUE THREAD

**Issue by Overwrite987** [hungnguyennaz/ZCord#15]
![image](https://user-images.githubusercontent.com/92237090/181465751-297d2af7-99f1-4a9a-8ef5-6f4d0a6eb145.png)

I think you know what to do

**Comment by hungnguyennaz** [comment]
Will try to fix it in next update.

**Comment by xIsm4** [comment]
> ![image](https://user-images.githubusercontent.com/92237090/181465751-297d2af7-99f1-4a9a-8ef5-6f4d0a6eb145.png)
> 
> I think you know what to do

stfu

**Comment by xIsm4** [comment]
https://github.com/hungnguyennaz/ZCord/commit/6710250d2e033e25bf0102f05649fd649d40a98f
